// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "worker_api.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace edu {
namespace princeton {
namespace jetstream {

namespace {

const ::google::protobuf::Descriptor* getTaskMeta_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  getTaskMeta_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_worker_5fapi_2eproto() {
  protobuf_AddDesc_worker_5fapi_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "worker_api.proto");
  GOOGLE_CHECK(file != NULL);
  getTaskMeta_descriptor_ = file->message_type(0);
  static const int getTaskMeta_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getTaskMeta, tid_),
  };
  getTaskMeta_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      getTaskMeta_descriptor_,
      getTaskMeta::default_instance_,
      getTaskMeta_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getTaskMeta, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getTaskMeta, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(getTaskMeta));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_worker_5fapi_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    getTaskMeta_descriptor_, &getTaskMeta::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_worker_5fapi_2eproto() {
  delete getTaskMeta::default_instance_;
  delete getTaskMeta_reflection_;
}

void protobuf_AddDesc_worker_5fapi_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::edu::princeton::jetstream::protobuf_AddDesc_jetstream_5ftypes_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020worker_api.proto\022\027edu.princeton.jetstr"
    "eam\032\025jetstream_types.proto\";\n\013getTaskMet"
    "a\022,\n\003tid\030\001 \002(\0132\037.edu.princeton.jetstream"
    ".TaskID", 127);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "worker_api.proto", &protobuf_RegisterTypes);
  getTaskMeta::default_instance_ = new getTaskMeta();
  getTaskMeta::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_worker_5fapi_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_worker_5fapi_2eproto {
  StaticDescriptorInitializer_worker_5fapi_2eproto() {
    protobuf_AddDesc_worker_5fapi_2eproto();
  }
} static_descriptor_initializer_worker_5fapi_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int getTaskMeta::kTidFieldNumber;
#endif  // !_MSC_VER

getTaskMeta::getTaskMeta()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void getTaskMeta::InitAsDefaultInstance() {
  tid_ = const_cast< ::edu::princeton::jetstream::TaskID*>(&::edu::princeton::jetstream::TaskID::default_instance());
}

getTaskMeta::getTaskMeta(const getTaskMeta& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void getTaskMeta::SharedCtor() {
  _cached_size_ = 0;
  tid_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

getTaskMeta::~getTaskMeta() {
  SharedDtor();
}

void getTaskMeta::SharedDtor() {
  if (this != default_instance_) {
    delete tid_;
  }
}

void getTaskMeta::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* getTaskMeta::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return getTaskMeta_descriptor_;
}

const getTaskMeta& getTaskMeta::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_worker_5fapi_2eproto();  return *default_instance_;
}

getTaskMeta* getTaskMeta::default_instance_ = NULL;

getTaskMeta* getTaskMeta::New() const {
  return new getTaskMeta;
}

void getTaskMeta::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_tid()) {
      if (tid_ != NULL) tid_->::edu::princeton::jetstream::TaskID::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool getTaskMeta::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .edu.princeton.jetstream.TaskID tid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_tid()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void getTaskMeta::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .edu.princeton.jetstream.TaskID tid = 1;
  if (has_tid()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->tid(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* getTaskMeta::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .edu.princeton.jetstream.TaskID tid = 1;
  if (has_tid()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->tid(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int getTaskMeta::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .edu.princeton.jetstream.TaskID tid = 1;
    if (has_tid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->tid());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void getTaskMeta::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const getTaskMeta* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const getTaskMeta*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void getTaskMeta::MergeFrom(const getTaskMeta& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_tid()) {
      mutable_tid()->::edu::princeton::jetstream::TaskID::MergeFrom(from.tid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void getTaskMeta::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void getTaskMeta::CopyFrom(const getTaskMeta& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool getTaskMeta::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  if (has_tid()) {
    if (!this->tid().IsInitialized()) return false;
  }
  return true;
}

void getTaskMeta::Swap(getTaskMeta* other) {
  if (other != this) {
    std::swap(tid_, other->tid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata getTaskMeta::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = getTaskMeta_descriptor_;
  metadata.reflection = getTaskMeta_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace jetstream
}  // namespace princeton
}  // namespace edu

// @@protoc_insertion_point(global_scope)
