// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker_api.proto

#ifndef PROTOBUF_worker_5fapi_2eproto__INCLUDED
#define PROTOBUF_worker_5fapi_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "jetstream_types.pb.h"
// @@protoc_insertion_point(includes)

namespace edu {
namespace princeton {
namespace jetstream {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_worker_5fapi_2eproto();
void protobuf_AssignDesc_worker_5fapi_2eproto();
void protobuf_ShutdownFile_worker_5fapi_2eproto();

class getTaskMeta;

// ===================================================================

class getTaskMeta : public ::google::protobuf::Message {
 public:
  getTaskMeta();
  virtual ~getTaskMeta();
  
  getTaskMeta(const getTaskMeta& from);
  
  inline getTaskMeta& operator=(const getTaskMeta& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const getTaskMeta& default_instance();
  
  void Swap(getTaskMeta* other);
  
  // implements Message ----------------------------------------------
  
  getTaskMeta* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const getTaskMeta& from);
  void MergeFrom(const getTaskMeta& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .edu.princeton.jetstream.TaskID tid = 1;
  inline bool has_tid() const;
  inline void clear_tid();
  static const int kTidFieldNumber = 1;
  inline const ::edu::princeton::jetstream::TaskID& tid() const;
  inline ::edu::princeton::jetstream::TaskID* mutable_tid();
  inline ::edu::princeton::jetstream::TaskID* release_tid();
  
  // @@protoc_insertion_point(class_scope:edu.princeton.jetstream.getTaskMeta)
 private:
  inline void set_has_tid();
  inline void clear_has_tid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::edu::princeton::jetstream::TaskID* tid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_worker_5fapi_2eproto();
  friend void protobuf_AssignDesc_worker_5fapi_2eproto();
  friend void protobuf_ShutdownFile_worker_5fapi_2eproto();
  
  void InitAsDefaultInstance();
  static getTaskMeta* default_instance_;
};
// ===================================================================


// ===================================================================

// getTaskMeta

// required .edu.princeton.jetstream.TaskID tid = 1;
inline bool getTaskMeta::has_tid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void getTaskMeta::set_has_tid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void getTaskMeta::clear_has_tid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void getTaskMeta::clear_tid() {
  if (tid_ != NULL) tid_->::edu::princeton::jetstream::TaskID::Clear();
  clear_has_tid();
}
inline const ::edu::princeton::jetstream::TaskID& getTaskMeta::tid() const {
  return tid_ != NULL ? *tid_ : *default_instance_->tid_;
}
inline ::edu::princeton::jetstream::TaskID* getTaskMeta::mutable_tid() {
  set_has_tid();
  if (tid_ == NULL) tid_ = new ::edu::princeton::jetstream::TaskID;
  return tid_;
}
inline ::edu::princeton::jetstream::TaskID* getTaskMeta::release_tid() {
  clear_has_tid();
  ::edu::princeton::jetstream::TaskID* temp = tid_;
  tid_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace jetstream
}  // namespace princeton
}  // namespace edu

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_worker_5fapi_2eproto__INCLUDED
