# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import jetstream_types_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='jetstream_controlplane.proto',
  package='edu.princeton.jetstream',
  serialized_pb='\n\x1cjetstream_controlplane.proto\x12\x17\x65\x64u.princeton.jetstream\x1a\x15jetstream_types.proto\"\xed\x01\n\tAlterTopo\x12\x32\n\x07toStart\x18\x01 \x03(\x0b\x32!.edu.princeton.jetstream.TaskMeta\x12\x34\n\x08toCreate\x18\x02 \x03(\x0b\x32\".edu.princeton.jetstream.TableMeta\x12\x33\n\ntaskToStop\x18\x03 \x03(\x0b\x32\x1f.edu.princeton.jetstream.TaskID\x12\x13\n\x0btableToStop\x18\x04 \x03(\t\x12,\n\x05\x65\x64ges\x18\x05 \x03(\x0b\x32\x1d.edu.princeton.jetstream.Edge\"\xb1\x01\n\rServerRequest\x12\x39\n\x04type\x18\x01 \x02(\x0e\x32+.edu.princeton.jetstream.ServerRequest.Type\x12\x31\n\x05\x61lter\x18\x03 \x01(\x0b\x32\".edu.princeton.jetstream.AlterTopo\"2\n\x04Type\x12\r\n\tGET_NODES\x10\x01\x12\n\n\x06\x44\x45PLOY\x10\x03\x12\x0f\n\x0b\x43OUNT_NODES\x10\x04\"g\n\x0eServerResponse\x12\x0e\n\x05\x65rror\x18\x93\x01 \x01(\t\x12/\n\x05nodes\x18\x94\x01 \x03(\x0b\x32\x1f.edu.princeton.jetstream.NodeID\x12\x14\n\x0b\x63ount_nodes\x18\x95\x01 \x01(\x05')



_SERVERREQUEST_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='edu.princeton.jetstream.ServerRequest.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='GET_NODES', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEPLOY', index=1, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='COUNT_NODES', index=2, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=448,
  serialized_end=498,
)


_ALTERTOPO = descriptor.Descriptor(
  name='AlterTopo',
  full_name='edu.princeton.jetstream.AlterTopo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='toStart', full_name='edu.princeton.jetstream.AlterTopo.toStart', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='toCreate', full_name='edu.princeton.jetstream.AlterTopo.toCreate', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='taskToStop', full_name='edu.princeton.jetstream.AlterTopo.taskToStop', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tableToStop', full_name='edu.princeton.jetstream.AlterTopo.tableToStop', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='edges', full_name='edu.princeton.jetstream.AlterTopo.edges', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=81,
  serialized_end=318,
)


_SERVERREQUEST = descriptor.Descriptor(
  name='ServerRequest',
  full_name='edu.princeton.jetstream.ServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='edu.princeton.jetstream.ServerRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='alter', full_name='edu.princeton.jetstream.ServerRequest.alter', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVERREQUEST_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=321,
  serialized_end=498,
)


_SERVERRESPONSE = descriptor.Descriptor(
  name='ServerResponse',
  full_name='edu.princeton.jetstream.ServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='edu.princeton.jetstream.ServerResponse.error', index=0,
      number=147, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nodes', full_name='edu.princeton.jetstream.ServerResponse.nodes', index=1,
      number=148, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count_nodes', full_name='edu.princeton.jetstream.ServerResponse.count_nodes', index=2,
      number=149, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=500,
  serialized_end=603,
)

_ALTERTOPO.fields_by_name['toStart'].message_type = jetstream_types_pb2._TASKMETA
_ALTERTOPO.fields_by_name['toCreate'].message_type = jetstream_types_pb2._TABLEMETA
_ALTERTOPO.fields_by_name['taskToStop'].message_type = jetstream_types_pb2._TASKID
_ALTERTOPO.fields_by_name['edges'].message_type = jetstream_types_pb2._EDGE
_SERVERREQUEST.fields_by_name['type'].enum_type = _SERVERREQUEST_TYPE
_SERVERREQUEST.fields_by_name['alter'].message_type = _ALTERTOPO
_SERVERREQUEST_TYPE.containing_type = _SERVERREQUEST;
_SERVERRESPONSE.fields_by_name['nodes'].message_type = jetstream_types_pb2._NODEID
DESCRIPTOR.message_types_by_name['AlterTopo'] = _ALTERTOPO
DESCRIPTOR.message_types_by_name['ServerRequest'] = _SERVERREQUEST
DESCRIPTOR.message_types_by_name['ServerResponse'] = _SERVERRESPONSE

class AlterTopo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALTERTOPO
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.AlterTopo)

class ServerRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERREQUEST
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.ServerRequest)

class ServerResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERRESPONSE
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.ServerResponse)

# @@protoc_insertion_point(module_scope)
