# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import jetstream_types_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='jetstream_dataplane.proto',
  package='edu.princeton.jetstream',
  serialized_pb='\n\x19jetstream_dataplane.proto\x12\x17\x65\x64u.princeton.jetstream\x1a\x15jetstream_types.proto\"A\n\x0cTableRequest\x12\x31\n\x05names\x18\x01 \x03(\x0b\x32\".edu.princeton.jetstream.TableName\">\n\rTableResponse\x12-\n\x06tables\x18\x01 \x02(\x0b\x32\x1d.edu.princeton.jetstream.Cube2i\n\x0cTableService\x12Y\n\x08getTable\x12%.edu.princeton.jetstream.TableRequest\x1a&.edu.princeton.jetstream.TableResponse')




_TABLEREQUEST = descriptor.Descriptor(
  name='TableRequest',
  full_name='edu.princeton.jetstream.TableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='names', full_name='edu.princeton.jetstream.TableRequest.names', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=77,
  serialized_end=142,
)


_TABLERESPONSE = descriptor.Descriptor(
  name='TableResponse',
  full_name='edu.princeton.jetstream.TableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tables', full_name='edu.princeton.jetstream.TableResponse.tables', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=206,
)

_TABLEREQUEST.fields_by_name['names'].message_type = jetstream_types_pb2._TABLENAME
_TABLERESPONSE.fields_by_name['tables'].message_type = jetstream_types_pb2._CUBE
DESCRIPTOR.message_types_by_name['TableRequest'] = _TABLEREQUEST
DESCRIPTOR.message_types_by_name['TableResponse'] = _TABLERESPONSE

class TableRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TABLEREQUEST
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.TableRequest)

class TableResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TABLERESPONSE
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.TableResponse)

# @@protoc_insertion_point(module_scope)
