# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='jetstream_types.proto',
  package='edu.princeton.jetstream',
  serialized_pb='\n\x15jetstream_types.proto\x12\x17\x65\x64u.princeton.jetstream\")\n\x06NodeID\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x02(\x0c\x12\x0e\n\x06portno\x18\x02 \x02(\x05\"-\n\x06TaskID\x12\x15\n\rcomputationID\x18\x01 \x02(\x05\x12\x0c\n\x04task\x18\x02 \x02(\x05\"s\n\x08TaskMeta\x12\x0b\n\x03\x63md\x18\x01 \x02(\t\x12+\n\x02id\x18\x02 \x02(\x0b\x32\x1f.edu.princeton.jetstream.TaskID\x12-\n\x04site\x18\x03 \x01(\x0b\x32\x1f.edu.princeton.jetstream.NodeID\"%\n\tTableName\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\"|\n\tTableMeta\x12\x30\n\x04name\x18\x01 \x02(\x0b\x32\".edu.princeton.jetstream.TableName\x12\x0e\n\x06schema\x18\x02 \x02(\t\x12-\n\x04site\x18\x03 \x01(\x0b\x32\x1f.edu.princeton.jetstream.NodeID\"!\n\x04\x45\x64ge\x12\x0b\n\x03src\x18\x01 \x02(\x05\x12\x0c\n\x04\x64\x65st\x18\x02 \x02(\x05\"\xd4\x01\n\x05Table\x12\x31\n\x04type\x18\x01 \x02(\x0e\x32#.edu.princeton.jetstream.Table.Type\x12\x30\n\x04meta\x18\x02 \x01(\x0b\x32\".edu.princeton.jetstream.TableMeta\x12\x11\n\tbytesData\x18\x03 \x03(\x0c\x12\x12\n\nstringData\x18\x04 \x03(\t\x12\x15\n\tint32Data\x18\x05 \x03(\x05\x42\x02\x10\x01\"(\n\x04Type\x12\t\n\x05\x42YTES\x10\x01\x12\n\n\x06STRING\x10\x02\x12\t\n\x05INT32\x10\x03\"6\n\x04\x43ube\x12.\n\x06tables\x18\x01 \x03(\x0b\x32\x1e.edu.princeton.jetstream.Table')



_TABLE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='edu.princeton.jetstream.Table.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='BYTES', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STRING', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INT32', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=630,
  serialized_end=670,
)


_NODEID = descriptor.Descriptor(
  name='NodeID',
  full_name='edu.princeton.jetstream.NodeID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='address', full_name='edu.princeton.jetstream.NodeID.address', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='portno', full_name='edu.princeton.jetstream.NodeID.portno', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=91,
)


_TASKID = descriptor.Descriptor(
  name='TaskID',
  full_name='edu.princeton.jetstream.TaskID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='computationID', full_name='edu.princeton.jetstream.TaskID.computationID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task', full_name='edu.princeton.jetstream.TaskID.task', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=93,
  serialized_end=138,
)


_TASKMETA = descriptor.Descriptor(
  name='TaskMeta',
  full_name='edu.princeton.jetstream.TaskMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cmd', full_name='edu.princeton.jetstream.TaskMeta.cmd', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='edu.princeton.jetstream.TaskMeta.id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='site', full_name='edu.princeton.jetstream.TaskMeta.site', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=140,
  serialized_end=255,
)


_TABLENAME = descriptor.Descriptor(
  name='TableName',
  full_name='edu.princeton.jetstream.TableName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='edu.princeton.jetstream.TableName.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='edu.princeton.jetstream.TableName.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=257,
  serialized_end=294,
)


_TABLEMETA = descriptor.Descriptor(
  name='TableMeta',
  full_name='edu.princeton.jetstream.TableMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='edu.princeton.jetstream.TableMeta.name', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='schema', full_name='edu.princeton.jetstream.TableMeta.schema', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='site', full_name='edu.princeton.jetstream.TableMeta.site', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=296,
  serialized_end=420,
)


_EDGE = descriptor.Descriptor(
  name='Edge',
  full_name='edu.princeton.jetstream.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='src', full_name='edu.princeton.jetstream.Edge.src', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dest', full_name='edu.princeton.jetstream.Edge.dest', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=422,
  serialized_end=455,
)


_TABLE = descriptor.Descriptor(
  name='Table',
  full_name='edu.princeton.jetstream.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='edu.princeton.jetstream.Table.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='meta', full_name='edu.princeton.jetstream.Table.meta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bytesData', full_name='edu.princeton.jetstream.Table.bytesData', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stringData', full_name='edu.princeton.jetstream.Table.stringData', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='int32Data', full_name='edu.princeton.jetstream.Table.int32Data', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TABLE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=458,
  serialized_end=670,
)


_CUBE = descriptor.Descriptor(
  name='Cube',
  full_name='edu.princeton.jetstream.Cube',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tables', full_name='edu.princeton.jetstream.Cube.tables', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=672,
  serialized_end=726,
)

_TASKMETA.fields_by_name['id'].message_type = _TASKID
_TASKMETA.fields_by_name['site'].message_type = _NODEID
_TABLEMETA.fields_by_name['name'].message_type = _TABLENAME
_TABLEMETA.fields_by_name['site'].message_type = _NODEID
_TABLE.fields_by_name['type'].enum_type = _TABLE_TYPE
_TABLE.fields_by_name['meta'].message_type = _TABLEMETA
_TABLE_TYPE.containing_type = _TABLE;
_CUBE.fields_by_name['tables'].message_type = _TABLE
DESCRIPTOR.message_types_by_name['NodeID'] = _NODEID
DESCRIPTOR.message_types_by_name['TaskID'] = _TASKID
DESCRIPTOR.message_types_by_name['TaskMeta'] = _TASKMETA
DESCRIPTOR.message_types_by_name['TableName'] = _TABLENAME
DESCRIPTOR.message_types_by_name['TableMeta'] = _TABLEMETA
DESCRIPTOR.message_types_by_name['Edge'] = _EDGE
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
DESCRIPTOR.message_types_by_name['Cube'] = _CUBE

class NodeID(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODEID
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.NodeID)

class TaskID(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKID
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.TaskID)

class TaskMeta(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKMETA
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.TaskMeta)

class TableName(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TABLENAME
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.TableName)

class TableMeta(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TABLEMETA
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.TableMeta)

class Edge(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EDGE
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.Edge)

class Table(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TABLE
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.Table)

class Cube(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CUBE
  
  # @@protoc_insertion_point(class_scope:edu.princeton.jetstream.Cube)

# @@protoc_insertion_point(module_scope)
